### PR TITLE
Some Changes

### PR DESCRIPTION
**Pull request by LocalGoddess**

### CODE REVIEW

**Comment by BlazeMCworld** [comment]
main question is: what does this achieve

**Comment by Hammer86gn** [comment]
> main question is: what does this achieve

Config is now a singleton so you don't have a bunch of objects everywhere & project now uses shadow

**Review by TechStreetDev — APPROVED** [review]

**Comment by BlazeMCworld** [comment]
ok so config being a singleton i can understand, but whats the point of shadow if we arent shadowing anything and why did you change other unrelated things

**Comment by Hammer86gn** [comment]
I changed NBSDecorder.java to better follow the GNU Lesser General Public License

**Comment by BlazeMCworld** [comment]
i saw that, but with unrelated i mean adding things like .this when it isnt needed

**Comment by Hammer86gn** [comment]
That's just force of habit

**Comment by BlazeMCworld** [comment]
ok so then thats cleared up, only leaves 1 thing: why shadow if we arent shadowing anything

**Comment by Hammer86gn** [comment]
I'll remove that

**Review by BlazeMCworld — APPROVED** [review]

**Comment by BlazeMCworld** [comment]
approved, now just waiting incase some other dev wants to request some changes before merging

**Comment by TechStreetDev** [comment]
No one else viewed it so i merged

**Pull request merged**
